-- LƯU Ý: SAU NÀY CÓ HỌC INDEX XONG THÌ QUAY VỀ THỬ INDEX VỚI SELECT DISTINCT

-- VIẾT CÂU LỆNH LẤY RA TÊN CÁC QUỐC GIA KHÁC NHAU TỪ BẢNG KHÁCH HÀNG
SELECT DISTINCT Country 
FROM Customers

-- VIẾT CÂU LỆNH LẤY RA TÊN CÁC MÃ SỐ BƯU ĐIỆN KHÁC NHAU TỪ BẢNG NHÀ CUNG CẤP
SELECT DISTINCT PostalCode 
FROM Suppliers

-- VIẾT CÂU LỆNH LẤY RA CÁC DỮ LIỆU KHÁC NHAU VỀ HỌ CỦA NHÂN VIÊN VÀ CÁCH GỌI DANH HIỆU LỊCH SỰ CỦA NHÂN VIÊN
SELECT DISTINCT LastName, TitleOfCourtesy 
FROM Employees

-- VIẾT CÂU LỆNH LẤY RA MÃ ĐƠN VỊ VẬN CHUYỂN KHÁC NHAU CỦA CÁC ĐƠN HÀNG
SELECT DISTINCT ShipVia
FROM Orders

-- VIẾT CÂU LỆNH LẤY RA SỐ FAX KHÁC NHAU TRONG BẢNG CUSTOMERS
SELECT DISTINCT Fax 
FROM Customers

-- VIẾT CÂU LỆNH LẤY RA ĐƠN GIÁ CỦA CÁC SẢN PHẨM TRONG BẢNG PRODUCTS
SELECT DISTINCT UnitPrice
FROM Products
