-- LẤY RA TẤT CẢ CÁC ĐƠN HÀNG CHƯA ĐƯỢC GIAO HÀNG (SHIPPEDDATE = NULL)
SELECT *
FROM Orders
WHERE ShippedDate IS NULL

SELECT COUNT(*)
FROM Orders
WHERE ShippedDate IS NULL

-- LẤY DANH SÁCH CÁC KHÁCH HÀNG CÓ KHU VỰC KHÔNG BỊ NULL
SELECT *
FROM Customers
WHERE Region IS NOT NULL

-- LẤY RA DANH SÁCH CÁC KHÁCH HÀNG KHÔNG CÓ TÊN CÔNG TY
SELECT *
FROM Customers
WHERE CompanyName IS NULL

-- LẤY RA TẤT CẢ CÁC ĐƠN HÀNG CHƯA ĐƯỢC GIAO HÀNG VÀ CÓ KHU VỰC GIAO HÀNG KHÔNG BỊ NULL
SELECT *
FROM Orders
WHERE ShippedDate IS NULL AND ShipRegion IS NOT NULL
