-- VÍ DỤ 1:
CREATE DATABASE MYDATABASE;

-- CÂU VÍ DỤ MẪU
--CREATE DATABASE EMPLOYEES
--ON 
--(NAME = 'EMPLOYEES_DATA', TÊN FILE LƯA TRỮ
--	FILENAME = '...mdf', VỊ TRÍ LƯU TRỮ
--	SIZE = 10MB, KÍCH CỠ FILE
--	MAXSIZE = 100MB, KÍCH THƯỚC TỐI ĐA
--	FILEGROWTH = 5MB) MỖI KHI THÊM DỮ LIỆU THÌ CỘNG THÊM ...
--LOG ON
--(NAME = 'EMPLOYEES_LOG', 
--	FILENAME = '...ldf',
--	SIZE = 5MB,
--	MAXSIZE = 50MB,
--	FILEGROWTH = 1MB);


CREATE DATABASE NVDB
ON
(NAME = 'NVDB_DATA',
	FILENAME = '',
	SIZE = 10MB, 
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB)
LOG ON
(NAME = 'NVDB_LOG', 
	FILENAME = '',
	SIZE = 5MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 1MB);