--CREATE TABLE TenBang (
--    TenCot KieuDuLieu(DoDai) NULL | NOT NULL,
    
--    CONSTRAINT Ten_PK PRIMARY KEY (TenCot),
--    CONSTRAINT Ten_FK FOREIGN KEY (TenCot)
--    REFERENCES BangKhac(TenCot)
--);

-- MỘT SỐ LỆNH BỔ SUNG KHI TẠO BẢNG
-- IDENTITY: TẠO CỘT TỰ TĂNG
-- IDENTITY: TẠO CỘT TỰ TĂNG VỚI GIÁ TRỊ SEED VÀ INCREMENT
-- DEFAULT: THIẾT LẬP GIÁ TRỊ MẶC ĐỊNH
-- CHECK: THIẾT LẬP RÀNG BUỘC KIỂM TRA CỘT
-- UNIQUE: THIỆT LẬP RÀNG BUỘC DUY NHẤT CHO CỘT



CREATE TABLE NHANVIEN(
	MaNV INT PRIMARY KEY,
	HoTen VARCHAR(50) NOT NULL,
	Phai VARCHAR(50),
	NgaySinh DATE,
	DiaChi VARCHAR(255),
	SDT VARCHAR(10)
)


CREATE TABLE KHACHHANG(
	MaKH INT IDENTITY(100,5) PRIMARY KEY,
	TenKH VARCHAR(50) NOT NULL,
	DiaChi VARCHAR(255),
	SDT VARCHAR(10) CHECK (SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
)

-- CÚ PHÁP THAY ĐỔI CẤU TRÚC TABLE
/* =========================================
   ALTER TABLE - TỔNG QUÁT
========================================= */

---- 1. THÊM CỘT
--ALTER TABLE TenBang
--ADD TenCot KieuDuLieu(DoDai) NULL | NOT NULL;

---- Ví dụ
--ALTER TABLE Customers
--ADD Address NVARCHAR(200) NULL;



---- 2. SỬA CỘT (ĐỔI KIỂU DỮ LIỆU / NULL)
--ALTER TABLE TenBang
--ALTER COLUMN TenCot KieuDuLieu(DoDai) NULL | NOT NULL;

---- Ví dụ
--ALTER TABLE Customers
--ALTER COLUMN CustomerName NVARCHAR(150) NOT NULL;



---- 3. XÓA CỘT
--ALTER TABLE TenBang
--DROP COLUMN TenCot;

---- Ví dụ
--ALTER TABLE Customers
--DROP COLUMN Address;



---- 4. THÊM PRIMARY KEY
--ALTER TABLE TenBang
--ADD CONSTRAINT Ten_PK PRIMARY KEY (TenCot);

---- Ví dụ
--ALTER TABLE Customers
--ADD CONSTRAINT PK_Customers PRIMARY KEY (CustomerID);



---- 5. THÊM FOREIGN KEY
--ALTER TABLE TenBang
--ADD CONSTRAINT Ten_FK FOREIGN KEY (TenCot)
--REFERENCES BangKhac(TenCot);

---- Ví dụ
--ALTER TABLE Orders
--ADD CONSTRAINT FK_Orders_Customers
--FOREIGN KEY (CustomerID)
--REFERENCES Customers(CustomerID);



---- 6. XÓA CONSTRAINT
--ALTER TABLE TenBang
--DROP CONSTRAINT TenConstraint;

---- Ví dụ
--ALTER TABLE Orders
--DROP CONSTRAINT FK_Orders_Customers;



---- 7. THÊM CHECK
--ALTER TABLE TenBang
--ADD CONSTRAINT Ten_Check CHECK (DieuKien);

---- Ví dụ
--ALTER TABLE Products
--ADD CONSTRAINT CK_Product_Price CHECK (Price > 0);



---- 8. THÊM DEFAULT
--ALTER TABLE TenBang
--ADD CONSTRAINT Ten_Default DEFAULT GiaTri FOR TenCot;

---- Ví dụ
--ALTER TABLE Users
--ADD CONSTRAINT DF_Users_Status DEFAULT 'Active' FOR Status;

ALTER TABLE NHANVIEN
ADD Email VARCHAR(100);

ALTER TABLE NHANVIEN
ALTER COLUMN HoTen VARCHAR(100);


ALTER TABLE NHANVIEN
ADD CONSTRAINT NgaySinhCheck CHECK (NgaySinh <= GETDATE());


-- XÓA TOÀN BỘ DỮ LIỆU NHƯNG KHÔNG XÓA DỮ LIỆU

-- TRUNCATE TABLE [TÊN BẢNG];

-- XÓA TOÀN BỘ BẢNG

-- DROP TABLE [TÊN BẢNG];

TRUNCATE TABLE NHANVIEN

DROP TABLE NHANVIEN

-- BÀI TẬP

DBCC CHECKIDENT ('SINHVIEN');

DBCC CHECKIDENT ('SINHVIEN', RESEED, 0);

-- 1. TẠO TABLE SINH VIÊN
CREATE TABLE SINHVIEN(
	MA_SV INT IDENTITY NOT NULL PRIMARY KEY,
	HO_TEN VARCHAR(50) NOT NULL,
	LOP VARCHAR(20),
	NGANH VARCHAR(20),
	DIEM_TB FLOAT
);

-- 2. THÊM CỘT EMAIL VÀO BẢNG
ALTER TABLE SINHVIEN
ADD EMAIL VARCHAR(100)

-- 3. SỬA KIỂU DỮ LIỆU ĐIỂM TB 
ALTER TABLE SINHVIEN
ALTER COLUMN DIEM_TB DECIMAL(3,1)

-- 4. XÓA CỘT NGÀNH
ALTER TABLE SINHVIEN
DROP COLUMN NGANH

-- 5. THÊM RÀNG BUỘC KIỂM TRA GIÁ TRỊ CHO DIEM_TB
ALTER TABLE SINHVIEN
DROP CONSTRAINT CHECK_DIEM_TB 


ALTER TABLE SINHVIEN
ADD CONSTRAINT CHECK_DIEM_TB CHECK (DIEM_TB BETWEEN 0 AND 10)

-- 6. THÊM RÀNG BUỘC DUY NHẤT CHO TÊN
ALTER TABLE SINHVIEN
ADD CONSTRAINT UNIQUE_NAME UNIQUE (HO_TEN)

-- 7. THÊM DỮ LIỆU

-- 8. XÓA DỮ LIỆU BẢNG
TRUNCATE TABLE SINHVIEN

-- 9. XÓA BẢNG
DROP TABLE SINHVIEN



















