-- DÙNG ĐỂ TẠO RA BẢNG MỚI VÀ  SAO CHÉP DỮ LIỆU TỪ MỘT BẢNG HIỆN CÓ ĐẾN BẢNG MỚI
-- THƯỜNG ĐƯỢC SỬ DỤNG ĐỂ TẠO BẢNG TẠM THỜI 

-- CÚ PHÁP

--SELECT *
--INTO NEW_TABLE [IN EXTERNALDB]
--FROM OLD_TABLE
--WHERE CONDITION


--SELECT COL1, COL2, COL3, ...
--INTO NEW_TABLE [IN EXTERNALDB]
--FROM OLD_TABLE
--WHERE CONDITION

-- TẠO RA BẢNG MỚI VỚI CÁC SẢN PHẨM CÓ GIÁ > 50
SELECT *
INTO HIGH_VALUE_PRODUCTS
FROM Products
WHERE UnitPrice > 50

-- TẠO BẢNG MỚI CÁC ĐƠN HÀNG ĐƯỢC GIAO ĐẾN USA
SELECT *
INTO USA_ORDERS
FROM Orders
WHERE ShipCountry LIKE 'USA'

-- BÀI TẬP
-- TẠO MỘT BẢNG TẠM THỜI ĐỂ CHỨA THÔNG TIN KHÁCH HÀNG ĐẾN TỪ LONDON
SELECT *
INTO CUSTOMERS_IN_LONDON
FROM Customers
WHERE City LIKE 'LONDON'

-- TẠO 1 BẢNG TẠM THỜI ĐỂ LƯU CHỨA THÔNG TIN ĐƠN HÀNG CÓ TỔNG GIÁ TRỊ MẶT HÀNG LỚN HƠN 1000 ĐÔ LA
WITH CTE AS (
	SELECT D.OrderID, SUM(D.UnitPrice * D.UnitPrice) AS 'TONG TIEN'
	FROM [Order Details] AS D
	GROUP BY D.OrderID
) 
SELECT O.*, D.[TONG TIEN]
INTO HIGH_VALUE_ORDERS
FROM Orders AS O
JOIN CTE AS D
ON O.OrderID = D.OrderID
WHERE D.[TONG TIEN] > 1000








