-- LÀ TẬP HỢP MỘT HOẶC NHIỀU CÂU LỆNH T-SQL THÀNH MỌT NHÓM ĐƠN VỊ XỬ LÝ LOGIC VÀ ĐƯỢC LƯU TRỮ TRÊN DATABASE SERVER
-- KHI CHẠY LẦN ĐẦU TIÊN THÌ SQL SERVER SẼ CHẠY NÓ VÀ LƯU TRỮ VÀO BỘ NHỚ ĐỆM, GỌI LÀ PLAN CACHE, NHỮNG LẦN TIẾP THEO THÌ SỬ DỤNG LẠI TRONG PLAN CACHE


-- GIÚP CHO DBA TẠO RA NHỮNG NHÓM CÂU LỆNH VÀ GỬI ĐẾN NHIỀU BỘ PHẬN KHÁC MÀ HỌ SẼ KHÔNG CẦN QUAN TÂM ĐẾN NỘI DUNG BÊN TRONG

-- CÚ PHÁP

--CREATE PROCEDURE DATABASE_NAME.SCHEMA_NAME.PROCEDURE_NAME
--(
--	PARAMETER_1 DATATYPE, PARAMETER_2 DATATYPE
--)
--AS
--BEGIN
--	STATEMENTS
--END

-- TẠO MỘT STORED PROCEDURE ĐỂ LẤY THÔNG TIN 
-- VỀ SẢN PHẨM DỰA TRÊN TÊN SẢN PHẨM ĐƯỢC CUNG CẤP
CREATE PROCEDURE GET_PRODUCT_NAME
	@PRODUCT_NAME NVARCHAR(100)
AS
BEGIN 
	SELECT * FROM Products
	WHERE ProductName = @PRODUCT_NAME
END


-- SỬ DỤNG
EXEC GET_PRODUCT_NAME @PRODUCT_NAME = 'IKURA'
EXEC GET_PRODUCT_NAME @PRODUCT_NAME = 'CHAI'

-- EXEC không trả về dataset dạng table expression

--  TẠO MỘT STORED PROCEDURE ĐỂ TÍNH TỔNG DOANH SỐ BÁN HÀNG
-- CỦA MỘT NHÂN VIÊN DỰA VÀO EMPLOYEE_ID

CREATE PROCEDURE GET_SALES_TOTAL_EMPLOYEES 
	@EMPLOYEE_ID INT
AS
BEGIN
	SELECT SUM(D.Quantity * D.UnitPrice) AS 'TOTAL SALES'
	FROM Orders AS O
	JOIN [Order Details] AS D
	ON O.OrderID = D.OrderID
	WHERE EmployeeID = @EMPLOYEE_ID
END

-- THỰC THI
EXEC GET_SALES_TOTAL_EMPLOYEES @EMPLOYEE_ID = 1
EXEC GET_SALES_TOTAL_EMPLOYEES @EMPLOYEE_ID = 2
EXEC GET_SALES_TOTAL_EMPLOYEES @EMPLOYEE_ID = 3


-- TẠO MỘT STORED PROCEDURE ĐỂ THÊM MỚI KHÁCH HÀNG VÀO BẢNG CUSTOMERS
CREATE PROCEDURE ADD_CUSTOMER
	@CUSTOMER_ID NVARCHAR(5),
	@COMPANY_NAME NVARCHAR(40),
	@CONTACT_NAME NVARCHAR(30),
	@CONTACT_TITLE NVARCHAR(30)
AS
BEGIN 
	INSERT INTO Customers (CustomerID, CompanyName, ContactName, ContactTitle)
	VALUES (@CUSTOMER_ID, UPPER(@COMPANY_NAME), @CONTACT_NAME, @CONTACT_TITLE)
END

-- THỰC THI
EXEC ADD_CUSTOMER 'NEWNV', 'TITV.VN', 'TUNG LE', 'MR.'


-- TẠO MỘT STORED PROCEDURE ĐỂ CẬP NHẬT GIÁ CỦA SẢN PHẨM  CỤ THỂ
CREATE PROCEDURE UPDATE_PRICE
	@PRODUCT_ID INT,
	@PRICE_INCREASE DECIMAL(10,2)
AS
BEGIN
	UPDATE Products
	SET UnitPrice = UnitPrice + @PRICE_INCREASE
	WHERE ProductID = @PRODUCT_ID
END

EXEC UPDATE_PRICE 1, 100




























